### ISSUE TITLE
System.TimeSpan encoded as "hh:mm:ss" string, but at decoding time a float is expected

### ISSUE THREAD

**Issue by anchann** [MangelMaxime/Thoth#152] opened 2019-07-10 01:44 UTC
I have the following type shared between the backend and front end.

```
type Config = {
    ....
    HistoryPeriod: System.TimeSpan
}
```

On the backend, this is encoded using `Thoth.Json.Net` and sent across the wire to a Fable app, where `Thoth.Json` is used to decode it into the same `Config` type defined above. At decode time, I get the following error:

```
Error at: `$.Config.HistoryPeriod`
Expecting a float but instead got: "01:00:00"
```

I spent a bunch of time debugging this, and it seems like there may be some asymmetry happening between Thoth and (maybe?) Fable. The former, on the backend, decides to do a custom string encoding, but on the front end (JS runtime) seems to rely on reflection info that's generated by (I think) Fable, which looks like this:

```
export function Config$reflection() {
    return record("LibInfraHealth.Types.Config", [], Config, () => [
        ...
        ["HistoryPeriod", float64],
    ]);
}
```

So the decoder decides it wants a float. For what it's worth, Fable lists https://fable.io/docs/compatibility.html that `System.TimeSpan` is represented as `number`.

Am I understanding this correctly? What's the right way to get all this working?

I'm pretty sure it shouldn't matter, but I had to hack together an `OutputFormatter` wrapper over `Thoth.Json.Net` to get it working with ASP.NET Core MVC, based on the `Thoth.Json.Giraffe` implementation.

**Comment by MangelMaxime** [comment] 2019-07-24 14:17
> So the decoder decides it wants a float. For what it's worth, Fable lists https://fable.io/docs/compatibility.html that System.TimeSpan is represented as number.

I think you are on the right track with this.

It seems like a bug in Fable.

```fs
open Fable.Core
open Thoth.Json
open System

let json = 
    TimeSpan.FromHours(10.)
    |> Encode.timespan
    |> Encode.toString 0

let value =
    Decode.Auto.fromString<TimeSpan> json

JS.console.log(value)
```

generates:

```js
import { float64 } from "fable-library/Reflection.js";
import { fromHours } from "fable-library/TimeSpan.js";
import { Auto$$$fromString$$Z33228D48 as Auto$0024$0024$0024fromString$0024$0024Z33228D48 } from "fable-repl-lib/src/Decode";
import { toString, timespan } from "fable-repl-lib/src/Encode";
export const json = toString(0, timespan(fromHours(10)));
export const value = Auto$0024$0024$0024fromString$0024$0024Z33228D48(json, null, null, {
  ResolveType() {
    return float64;
  }

});
console.log(value);
```

See how `ResolveType` is returning instead of `return type("System.TimeSpan")`.

**Comment by MangelMaxime** [comment] 2019-07-26 16:18
cc @anchann @isaacabraham 

Fable 2.3.14 has been released. https://github.com/fable-compiler/Fable/releases/tag/2.3.14

Can you please confirm that this fixed the issue?

**Comment by anchann** [comment] 2019-07-29 05:59
Hi, thank you for looking into this.

I've pulled in 2.3.14 into my project. Decoding no longer fails, but there's a number of other issues that I've come across:

* Decoding (in the JS runtime) of negative `TimeSpan`s (that were successfully produced by encoding in the dotnet runtime) fails
* Encoding in the JS runtime fails, producing a number of some sort (so I imagine trying to send values back to the server would fail on decode)
* Decoding (in the JS runtime) of values that contain milliseconds seems buggy. On the right is the value produced by encoding on the dotnet side, on the left is the result of calling `TotalSeconds` on the decoded value. Things seem off by a few orders of magnitude, but also notice the situation with the second line.

```
"00:00:00.0278460" -> 278.46
"00:02:00.0156900" -> 276.9
"00:00:00.0156800" -> 156.8
"00:00:00.0277320" -> 277.32
"00:00:00.0277400" -> 277.4
"00:00:00.0277050" -> 277.05
```

I'm under some time pressure, so can't do more digging at the moment, sorry. Reverting to working with raw milliseconds for now.

**Comment by MangelMaxime** [comment] 2019-07-29 07:24
Thoth.Json is doing nothing special, it's calling `TimeSpan.Tryparse` so I guess the `TimeSpan` implementation is broken and so this is a bug in Fable.

**Comment by anchann** [comment] 2019-07-29 07:28
You seem to already have a working relationship with the author of fable — may I ask you to propagate the bug report there? If not, I'll eventually get to writing up the report.

**Comment by MangelMaxime** [comment] 2019-07-29 11:12
> Decoding (in the JS runtime) of negative TimeSpans (that were successfully produced by encoding in the dotnet runtime) fails

Negative TimeSpan parsing is not implemented in Fable, I have a fix for it.

> Encoding in the JS runtime fails, producing a number of some sort (so I imagine trying to send values back to the server would fail on decode)

I can't reproduce or don't understand the problem. Can you please provide me with a set of examples?

**Comment by isaacabraham** [comment] 2019-07-29 13:15
I tried upgrading to the newer version and everything just worked for us. Although we weren't using negative timespans!

**Comment by MangelMaxime** [comment] 2019-07-29 18:57
@anchann I have a PR https://github.com/fable-compiler/Fable/pull/1867 fixing point 1 and 3 of your list.

But I can't fix point 2 because I can't repro it.

**Comment by anchann** [comment] 2019-07-30 00:50
@MangelMaxime thank you for fixing 1 and 3.

I tried to put together a repro case for 2 in the REPL. Please let me know if my expectations are off.

```
open Fable.Core
open Thoth.Json
open System

let timespan = TimeSpan.FromSeconds(5.0)

JS.console.log("timespan")
JS.console.log(timespan)

let timespanStringified = Encode.Auto.toString(0, timespan)

JS.console.log("timespanStringified")
JS.console.log(timespanStringified)
```

this produces the following output, as it does on the dotnet runtime:

```
timespan
5000
timespanStringified
5000
```

I would have expected it to produce the following output:

```
timespan
5000
timespanStringified
"00:00:05"
```

I also briefly wondered if `toString` in some way fails to infer time correctly at runtime (sorry, don't fully know how this stuff works), so I tried supplying a type manually:

```
let timespanStringifiedTyped = Encode.Auto.toString<TimeSpan>(0, timespan)

JS.console.log("timespanStringifiedTyped")
JS.console.log(timespanStringifiedTyped)
```

but this still produced output that didn't match expectations

```
timespanStringifiedTyped
5000
```

**Comment by MangelMaxime** [comment] 2019-07-30 06:06
@anchann Thank you for the example.

Did you run it against latest version of Fable 2..3.14? Because here it seems like it's using the `float` encoder instead of the `timespan` encoder which match with the problem I fixed first in the reflection API.

**Comment by anchann** [comment] 2019-07-30 06:27
@MangelMaxime just tried running against a local copy of the repl where I updated the version of `fable-compiler` to `2.3.14` in `package.json` (verified by hovering a random file in dev tools — it does seem to come from the right version: `http://localhost:8080/js/repl/lib/fable-library.2.3.14/Reflection.js`). The results are the same as what I posted. Hopefully I'm not screwing anything up in my testing.

**Comment by anchann** [comment] 2019-07-30 06:32
Hmm, actually, as another check, I tried adding a decode test:

```
let decodeTest = Decode.Auto.fromString<TimeSpan> "\"00:15:42\""
JS.console.log(decodeTest)
```

this should work in `2.3.14`, as verified within my app, but should fail in `2.3.10`, as it did before. In my local repl, it fails with

```
Error at: `$`↵Expecting a float but instead got: "00:15:42"
```

So... I don't know what to think. I've definitely successfully decoded this format with `2.3.14`, yet in this repl it's failing.

Do you know how I can verify that I'm indeed using `2.3.14` in the repl?

**Comment by anchann** [comment] 2019-07-30 06:35
I'm wondering if the repl has two separate instances of `fable-compiler`, one with which the repl app itself is built, and one which the user's input is piped into for evaluation. This is just a guess...

**Comment by MangelMaxime** [comment] 2019-07-30 06:50
There do have 2 instances indeed.

You have the instance used to compile the REPL itself like any Fable project.

And then when you run code from the browser it's another instance hosted directly in the browser which uses a custom version of the F# and Fable compiler.

To test your code its in general easier to start a fresh project. Because it's easier to set up and check that everything is ok ^^.

But because, I don't have tests for `TimeSpan` and `Auto` coder, I will add them to the repos and will see what the CI says :)

**Comment by anchann** [comment] 2019-07-30 06:58
Awesome, thank you.

Ideally the REPL would allow one to choose the version the user's code is compiled with, but I imagine this is a nontrivial change.

**Comment by MangelMaxime** [comment] 2019-07-30 15:34
Everything should be fixed with `fable-compiler@2.3.15`

If there is still a bug or you discover a new one about `TimeSpan` please open it on [Fable](https://github.com/fable-compiler/fable) repo.

Unless it's due to json serialisation/deserialization but the CIs pass the tests so it should works.

**Closed by MangelMaxime** 2019-07-30 15:34 UTC

**Comment by anchann** [comment] 2019-07-30 23:37
@MangelMaxime Thank you! I've tried it out, and things seem to be mostly working, except for the serialization of negative values in the JS runtime.

```
Thoth.Json.Encode.Auto.toString(4, TimeSpan.FromSeconds -153.0)
```

produces this:

```
"-1.-1:-3:-33"
```

**Comment by MangelMaxime** [comment] 2019-08-01 18:40
Fixed by latest version of Fable

**Comment by anchann** [comment] 2019-08-02 00:44
Thank you very much, verified to be working correctly.
